-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  SaaS Этап 0 — Postgres-схема (СГЕНЕРИРОВАНО из боевой SQLite).     ║
-- ║  Текущий салон при миграции = tenant_id 1.                         ║
-- ║  НЕ редактировать руками — править generate.py и пересобирать.      ║
-- ╚══════════════════════════════════════════════════════════════════╝

-- ── 0. Реестр тенантов и биллинг платформы (новое) ───────────────────────
CREATE TABLE tenants (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug               TEXT UNIQUE NOT NULL,
  display_name       TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'trial',
  plan               TEXT NOT NULL DEFAULT 'start',
  brand              JSONB NOT NULL DEFAULT '{}',
  provider           TEXT NOT NULL DEFAULT 'yclients',
  provider_config    BYTEA,
  active_master_ids  JSONB NOT NULL DEFAULT '[]',
  bot_mode           TEXT NOT NULL DEFAULT 'shared',
  bot_config         BYTEA,
  admin_tg_ids       JSONB NOT NULL DEFAULT '[]',
  payments_config    BYTEA,
  settings           JSONB NOT NULL DEFAULT '{}',
  locale             TEXT NOT NULL DEFAULT 'ru',
  timezone           TEXT NOT NULL DEFAULT 'Europe/Moscow',
  trial_ends_at      TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  billing_method_id  TEXT,
  owner_email        TEXT,
  owner_phone        TEXT,
  owner_tg_id        BIGINT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tenant_invoices (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id          BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  period_start       DATE NOT NULL,
  period_end         DATE NOT NULL,
  plan               TEXT NOT NULL,
  amount_rub         BIGINT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'pending',
  yukassa_payment_id TEXT,
  paid_at            TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tenant_invoices_tenant ON tenant_invoices (tenant_id, period_start);

-- Подключённые допы-модули салона (конструктор тарифов). Ключи — plan_catalog.ADDONS.
CREATE TABLE tenant_addons (
  tenant_id  BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  addon_key  TEXT NOT NULL,
  active     BOOLEAN NOT NULL DEFAULT true,
  enabled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, addon_key)
);

-- Помесячный счётчик использования метрик-фич (CutMatch и др.) для квот и сверх-оплаты.
CREATE TABLE tenant_usage (
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  feature   TEXT NOT NULL,
  ym        TEXT NOT NULL,              -- '2026-06'
  count     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, feature, ym)
);

-- Текущий салон → tenant 1 (бренд/секреты заполнить отдельно скриптом миграции)
INSERT INTO tenants (id, slug, display_name)
  OVERRIDING SYSTEM VALUE VALUES (1, 'malesthetic', 'Мужская Эстетика');


-- ── 1. Доменные таблицы (+ tenant_id, per-tenant uniq) ──────────────────

CREATE TABLE admins (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  telegram_user_id BIGINT NOT NULL,
  added_at TEXT NOT NULL,
  added_by_user_id BIGINT,
  UNIQUE (
    tenant_id,
    telegram_user_id
  )
);

CREATE TABLE ai_advice_log (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  record_id BIGINT NOT NULL,
  client_id BIGINT,
  staff_id BIGINT NOT NULL,
  ai_provider TEXT, /* 'claude' | 'openai' | 'fallback' */
  advice_text TEXT,
  button_pressed TEXT, /* 'cash' | 'card' | NULL */
  payment_method TEXT,
  final_check_amount BIGINT, /* ₽ */
  created_at TEXT NOT NULL,
  closed_at TEXT,
  initial_services_json TEXT,
  final_services_json TEXT
);

CREATE TABLE ai_usage_log (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  at TEXT NOT NULL,
  feature TEXT NOT NULL,
  model TEXT NOT NULL,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  cache_read_tokens BIGINT NOT NULL DEFAULT 0,
  cache_write_tokens BIGINT NOT NULL DEFAULT 0,
  cost_usd REAL NOT NULL DEFAULT 0,
  user_id BIGINT
);

CREATE TABLE applogin_nonces (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  nonce TEXT PRIMARY KEY,
  created_at TEXT,
  chat_id BIGINT,
  token TEXT,
  consumed BIGINT DEFAULT 0
);

CREATE TABLE birthday_promo (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  percent BIGINT NOT NULL DEFAULT 20,
  year BIGINT NOT NULL,
  sent_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  UNIQUE (
    tenant_id,
    code
  )
);

CREATE TABLE bookings (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  service TEXT,
  master TEXT,
  datetime TEXT,
  yclients_record_id BIGINT,
  created_at TEXT
);

CREATE TABLE cash_log (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  date TEXT PRIMARY KEY, /* YYYY-MM-DD */
  total_till BIGINT NOT NULL, /* всего налички в кассе сейчас */
  day_cash BIGINT NOT NULL, /* наличкой получено за этот день */
  entered_by BIGINT,
  ts TEXT NOT NULL
);

CREATE TABLE client_chat_state (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT,
  last_client_message_at TEXT,
  last_client_message TEXT,
  last_ai_reply TEXT,
  last_ai_reply_at TEXT,
  resolved_reason TEXT,
  resolved_at TEXT,
  alerted_at TEXT,
  booking_intent BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, client_id)
);

CREATE TABLE client_history_cache (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT,
  history_json TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, client_id)
);

CREATE TABLE client_marketing_last (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT PRIMARY KEY,
  sent_at TEXT
);

CREATE TABLE client_preferences (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT PRIMARY KEY, /* clients.id (локальный) */
  prefs TEXT NOT NULL, /* по одному предпочтению на строку */
  updated_at TEXT NOT NULL
);

CREATE TABLE clients (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  telegram_chat_id BIGINT,
  name TEXT,
  phone TEXT,
  created_at TEXT,
  updated_at TEXT,
  name_enc TEXT,
  phone_enc TEXT,
  phone_hash TEXT,
  whats_new_seen_version TEXT,
  marketing_consent_at TEXT,
  marketing_consent_revoked_at TEXT,
  first_source TEXT,
  first_source_at TEXT,
  default_visit_mood TEXT,
  UNIQUE (
    tenant_id,
    telegram_chat_id
  )
);

CREATE TABLE consents (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  consent_given BIGINT NOT NULL,
  consent_at TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  source TEXT NOT NULL
);

CREATE TABLE cutmatch_usage (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  user_id BIGINT NOT NULL,
  day TEXT NOT NULL, /* YYYY-MM-DD */
  count BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, user_id, day)
);

CREATE TABLE cycle_reminder_log (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  avg_cycle_days BIGINT NOT NULL,
  predicted_visit TEXT NOT NULL,
  action TEXT NOT NULL DEFAULT 'sent', /* sent|engaged|declined|blocked */
  sent_at TEXT NOT NULL
);

CREATE TABLE freed_slot_offers (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  slot_datetime TEXT NOT NULL,
  offered_at TEXT NOT NULL,
  action TEXT NOT NULL
);

CREATE TABLE gift_certificates (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  code TEXT NOT NULL,
  amount BIGINT NOT NULL,
  recipient_phone TEXT NOT NULL,
  recipient_name TEXT,
  buyer_chat_id BIGINT,
  issued_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  used_by_admin_id BIGINT,
  payment_status TEXT NOT NULL DEFAULT 'pending',
  yukassa_payment_id TEXT,
  recipient_name_enc TEXT,
  recipient_phone_enc TEXT,
  recipient_phone_hash TEXT,
  UNIQUE (
    tenant_id,
    code
  )
);

CREATE TABLE loyalty_redeem_codes (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  code TEXT,
  client_id BIGINT NOT NULL,
  service_title TEXT NOT NULL,
  points BIGINT NOT NULL,
  issued_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  used_by_admin_id BIGINT,
  PRIMARY KEY (tenant_id, code)
);

CREATE TABLE loyalty_transactions (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  type TEXT NOT NULL,
  points BIGINT NOT NULL,
  visit_record_id BIGINT,
  note TEXT,
  at TEXT NOT NULL
);

CREATE TABLE master_push_subscriptions (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  staff_id BIGINT,
  telegram_chat_id BIGINT NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  subscription_json TEXT NOT NULL,
  user_agent TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE masters_telegram (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  yclients_staff_id BIGINT NOT NULL,
  telegram_chat_id BIGINT,
  full_name TEXT,
  bind_code TEXT,
  bound_at TEXT,
  is_active BIGINT NOT NULL DEFAULT 1,
  mute_until TEXT, /* ISO datetime, до этого момента уведомления глушим */
  created_at TEXT NOT NULL,
  can_redeem BIGINT NOT NULL DEFAULT 0,
  UNIQUE (
    tenant_id,
    yclients_staff_id
  ),
  UNIQUE (
    tenant_id,
    telegram_chat_id
  ),
  UNIQUE (
    tenant_id,
    bind_code
  )
);

CREATE TABLE maya_tenants (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT,
  plan TEXT,
  status TEXT NOT NULL DEFAULT 'pending', /* pending|active|suspended */
  owner_name TEXT,
  phone TEXT,
  mrr BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  activated_at TEXT
);

CREATE TABLE notify_prefs (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT PRIMARY KEY,
  prefs TEXT,
  updated_at TEXT
);

CREATE TABLE payment_idempotency (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  record_id BIGINT PRIMARY KEY,
  method TEXT NOT NULL,
  amount BIGINT,
  ts TEXT NOT NULL
);

CREATE TABLE processed_records (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  record_id BIGINT,
  event_type TEXT NOT NULL,
  processed_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, record_id)
);

CREATE TABLE reactivation_log (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  sent_at TEXT NOT NULL
);

CREATE TABLE record_state (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  record_id BIGINT,
  staff_id BIGINT,
  datetime TEXT,
  services_sig TEXT,
  attendance BIGINT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, record_id)
);

CREATE TABLE referral_codes (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  client_id BIGINT,
  code TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (
    tenant_id,
    code
  ),
  PRIMARY KEY (tenant_id, client_id)
);

CREATE TABLE referral_promos (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  referral_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  code TEXT NOT NULL,
  kind TEXT NOT NULL,
  percent BIGINT NOT NULL DEFAULT 15,
  issued_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  UNIQUE (
    tenant_id,
    code
  )
);

CREATE TABLE referrals (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  referrer_client_id BIGINT NOT NULL,
  referee_chat_id BIGINT NOT NULL,
  referee_client_id BIGINT,
  code_used TEXT NOT NULL,
  joined_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
);

CREATE TABLE review_requests (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  record_id BIGINT NOT NULL,
  staff_id BIGINT,
  visit_closed_at TEXT NOT NULL,
  send_after TEXT NOT NULL,
  sent_at TEXT,
  responded_at TEXT,
  rating BIGINT,
  comment TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  UNIQUE (
    tenant_id,
    client_id,
    record_id
  )
);

CREATE TABLE salon_expenses (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  date TEXT NOT NULL, /* YYYY-MM-DD (день, к которому относится расход) */
  item TEXT NOT NULL, /* что куплено/оплачено */
  amount BIGINT NOT NULL, /* рубли */
  source TEXT NOT NULL DEFAULT 'anton',
  created_at TEXT NOT NULL
);

CREATE TABLE salon_rules (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  rule_text TEXT NOT NULL,
  created_by BIGINT,
  created_at TEXT NOT NULL,
  active BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE settings (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  key TEXT,
  value TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, key)
);

CREATE TABLE slot_waitlist (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  chat_id BIGINT,
  staff_id BIGINT NOT NULL,
  slot_datetime TEXT NOT NULL, /* ISO 'YYYY-MM-DDTHH:MM' */
  created_at TEXT NOT NULL,
  notified_at TEXT
);

CREATE TABLE staff_messages (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  sender_chat_id BIGINT NOT NULL,
  sender_name TEXT,
  text TEXT NOT NULL,
  created_at TEXT NOT NULL,
  media_kind TEXT,
  media_url TEXT,
  media_name TEXT,
  media_mime TEXT,
  media_size BIGINT,
  media_dur REAL
);

CREATE TABLE stylist_consents (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  telegram_chat_id BIGINT,
  consent_given BIGINT NOT NULL,
  consent_at TEXT NOT NULL,
  consent_version TEXT NOT NULL,
  source TEXT NOT NULL
);

CREATE TABLE subscriptions (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  client_id BIGINT NOT NULL,
  plan_code TEXT NOT NULL,
  tier TEXT NOT NULL DEFAULT 'top',
  yukassa_payment_id TEXT,
  price_rub BIGINT NOT NULL,
  visits_included BIGINT NOT NULL,
  visits_used BIGINT NOT NULL DEFAULT 0,
  started_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_payment',
  payment_completed_at TEXT,
  renew_reminder_sent_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE tips (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  master_id BIGINT,
  master_slug TEXT,
  master_name TEXT,
  amount BIGINT NOT NULL DEFAULT 0,
  record_id BIGINT,
  created_at TEXT NOT NULL
);

CREATE TABLE tool_audit (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ts TEXT NOT NULL,
  user_id BIGINT,
  role TEXT,
  tool TEXT NOT NULL,
  risk TEXT,
  allowed BIGINT NOT NULL, /* 1 разрешено, 0 отказано гейтом */
  reason TEXT
);

CREATE TABLE visit_mood (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  record_id BIGINT PRIMARY KEY, /* YClients record_id */
  mood TEXT NOT NULL, /* 'red' | 'blue' */
  source TEXT, /* 'bot' | 'app' | 'admin' */
  client_id BIGINT, /* для пер-клиентской памяти (не обязателен) */
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE web_login_codes (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  phone_hash TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'call', /* 'call' | 'sms' */
  attempts BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT
);

CREATE TABLE web_sessions (
  tenant_id BIGINT NOT NULL DEFAULT CAST(CURRENT_SETTING('app.tenant_id') AS BIGINT) REFERENCES tenants (
    id
  ),
  token TEXT PRIMARY KEY,
  subject_kind TEXT NOT NULL DEFAULT 'client', /* 'client' | 'staff' */
  chat_id BIGINT,
  phone_hash TEXT,
  vk_user_id BIGINT,
  display_name TEXT,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  last_seen_at TEXT,
  revoked BIGINT NOT NULL DEFAULT 0,
  tg_first_name TEXT,
  tg_last_name TEXT,
  tg_username TEXT,
  tg_photo_url TEXT
);

-- ── 1a. UNIQUE(tenant_id, id) на родителях FK — для композитных FK ──
ALTER TABLE clients ADD CONSTRAINT uq_clients_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE referrals ADD CONSTRAINT uq_referrals_tenant_id UNIQUE (tenant_id, id);

-- ── 1b. Внешние ключи КОМПОЗИТНЫЕ (tenant_id + col) → parent(tenant_id, id) ──
-- 🔴 АУДИТ-ФИКС: запрещает ссылку на клиента ЧУЖОГО салона (FK обходил RLS).
ALTER TABLE birthday_promo ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE bookings ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE client_chat_state ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE consents ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE cycle_reminder_log ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE freed_slot_offers ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE loyalty_redeem_codes ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE loyalty_transactions ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE reactivation_log ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE referral_codes ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE referral_promos ADD FOREIGN KEY (tenant_id, referral_id) REFERENCES referrals (tenant_id, id);
ALTER TABLE referral_promos ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE referrals ADD FOREIGN KEY (tenant_id, referrer_client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE review_requests ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE stylist_consents ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);
ALTER TABLE subscriptions ADD FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id);

-- ── 2. Индексы (tenant_id впереди) ─────────────────────────────────────
CREATE INDEX idx_ai_usage_at ON ai_usage_log(tenant_id, at NULLS FIRST);
CREATE INDEX idx_ai_usage_feature ON ai_usage_log(tenant_id, feature NULLS FIRST);
CREATE INDEX idx_birthday_promo_client_year ON birthday_promo(tenant_id, client_id NULLS FIRST, year NULLS FIRST);
CREATE INDEX idx_client_chat_state_unresolved ON client_chat_state(tenant_id, resolved_at NULLS FIRST, alerted_at NULLS FIRST);
CREATE INDEX idx_freed_offers_client ON freed_slot_offers(tenant_id, client_id NULLS FIRST, offered_at NULLS FIRST);
CREATE INDEX idx_freed_offers_slot ON freed_slot_offers(tenant_id, slot_datetime NULLS FIRST);
CREATE INDEX idx_loyalty_codes_client ON loyalty_redeem_codes(tenant_id, client_id NULLS FIRST);
CREATE INDEX idx_loyalty_tx_client ON loyalty_transactions(tenant_id, client_id NULLS FIRST);
CREATE UNIQUE INDEX idx_loyalty_tx_earn_unique ON loyalty_transactions(tenant_id, client_id NULLS FIRST, visit_record_id NULLS FIRST, type NULLS FIRST) WHERE type = 'earn' AND NOT visit_record_id IS NULL;
CREATE INDEX idx_master_push_staff ON master_push_subscriptions(tenant_id, staff_id NULLS FIRST);
CREATE INDEX idx_referral_codes_code ON referral_codes(tenant_id, code NULLS FIRST);
CREATE INDEX idx_referrals_referee_chat ON referrals(tenant_id, referee_chat_id NULLS FIRST);
CREATE INDEX idx_referrals_referrer ON referrals(tenant_id, referrer_client_id NULLS FIRST);
CREATE INDEX idx_referrals_status ON referrals(tenant_id, status NULLS FIRST);
CREATE INDEX idx_review_requests_client ON review_requests(tenant_id, client_id NULLS FIRST);
CREATE INDEX idx_review_requests_status_send ON review_requests(tenant_id, status NULLS FIRST, send_after NULLS FIRST);
CREATE INDEX idx_salon_expenses_date ON salon_expenses(tenant_id, date NULLS FIRST);
CREATE INDEX idx_slot_waitlist_lookup ON slot_waitlist(tenant_id, staff_id NULLS FIRST, slot_datetime NULLS FIRST, notified_at NULLS FIRST);
CREATE INDEX idx_stylist_consents_client ON stylist_consents(tenant_id, client_id NULLS FIRST);
CREATE INDEX idx_subscriptions_client_status ON subscriptions(tenant_id, client_id NULLS FIRST, status NULLS FIRST);
CREATE INDEX idx_subscriptions_payment ON subscriptions(tenant_id, yukassa_payment_id NULLS FIRST);
CREATE INDEX idx_subscriptions_status_expires ON subscriptions(tenant_id, status NULLS FIRST, expires_at NULLS FIRST);
CREATE INDEX idx_web_login_codes_phone ON web_login_codes(tenant_id, phone_hash NULLS FIRST, expires_at NULLS FIRST);
CREATE INDEX idx_web_sessions_phone ON web_sessions(tenant_id, phone_hash NULLS FIRST);
CREATE INDEX idx_admins_tenant ON admins (tenant_id);
CREATE INDEX idx_ai_advice_log_tenant ON ai_advice_log (tenant_id);
CREATE INDEX idx_ai_usage_log_tenant ON ai_usage_log (tenant_id);
CREATE INDEX idx_applogin_nonces_tenant ON applogin_nonces (tenant_id);
CREATE INDEX idx_birthday_promo_tenant ON birthday_promo (tenant_id);
CREATE INDEX idx_bookings_tenant ON bookings (tenant_id);
CREATE INDEX idx_cash_log_tenant ON cash_log (tenant_id);
CREATE INDEX idx_client_chat_state_tenant ON client_chat_state (tenant_id);
CREATE INDEX idx_client_history_cache_tenant ON client_history_cache (tenant_id);
CREATE INDEX idx_client_marketing_last_tenant ON client_marketing_last (tenant_id);
CREATE INDEX idx_client_preferences_tenant ON client_preferences (tenant_id);
CREATE INDEX idx_clients_tenant ON clients (tenant_id);
CREATE INDEX idx_consents_tenant ON consents (tenant_id);
CREATE INDEX idx_cutmatch_usage_tenant ON cutmatch_usage (tenant_id);
CREATE INDEX idx_cycle_reminder_log_tenant ON cycle_reminder_log (tenant_id);
CREATE INDEX idx_freed_slot_offers_tenant ON freed_slot_offers (tenant_id);
CREATE INDEX idx_gift_certificates_tenant ON gift_certificates (tenant_id);
CREATE INDEX idx_loyalty_redeem_codes_tenant ON loyalty_redeem_codes (tenant_id);
CREATE INDEX idx_loyalty_transactions_tenant ON loyalty_transactions (tenant_id);
CREATE INDEX idx_master_push_subscriptions_tenant ON master_push_subscriptions (tenant_id);
CREATE INDEX idx_masters_telegram_tenant ON masters_telegram (tenant_id);
CREATE INDEX idx_maya_tenants_tenant ON maya_tenants (tenant_id);
CREATE INDEX idx_notify_prefs_tenant ON notify_prefs (tenant_id);
CREATE INDEX idx_payment_idempotency_tenant ON payment_idempotency (tenant_id);
CREATE INDEX idx_processed_records_tenant ON processed_records (tenant_id);
CREATE INDEX idx_reactivation_log_tenant ON reactivation_log (tenant_id);
CREATE INDEX idx_record_state_tenant ON record_state (tenant_id);
CREATE INDEX idx_referral_codes_tenant ON referral_codes (tenant_id);
CREATE INDEX idx_referral_promos_tenant ON referral_promos (tenant_id);
CREATE INDEX idx_referrals_tenant ON referrals (tenant_id);
CREATE INDEX idx_review_requests_tenant ON review_requests (tenant_id);
CREATE INDEX idx_salon_expenses_tenant ON salon_expenses (tenant_id);
CREATE INDEX idx_salon_rules_tenant ON salon_rules (tenant_id);
CREATE INDEX idx_settings_tenant ON settings (tenant_id);
CREATE INDEX idx_slot_waitlist_tenant ON slot_waitlist (tenant_id);
CREATE INDEX idx_staff_messages_tenant ON staff_messages (tenant_id);
CREATE INDEX idx_stylist_consents_tenant ON stylist_consents (tenant_id);
CREATE INDEX idx_subscriptions_tenant ON subscriptions (tenant_id);
CREATE INDEX idx_tips_tenant ON tips (tenant_id);
CREATE INDEX idx_tool_audit_tenant ON tool_audit (tenant_id);
CREATE INDEX idx_visit_mood_tenant ON visit_mood (tenant_id);
CREATE INDEX idx_web_login_codes_tenant ON web_login_codes (tenant_id);
CREATE INDEX idx_web_sessions_tenant ON web_sessions (tenant_id);

-- ── 3. Row-Level Security — изоляция тенантов на уровне БД ─────────────
-- Приложение в начале запроса делает: SET app.tenant_id = '<id>';
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON admins
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE ai_advice_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_advice_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ai_advice_log
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE ai_usage_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ai_usage_log
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE applogin_nonces ENABLE ROW LEVEL SECURITY;
ALTER TABLE applogin_nonces FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON applogin_nonces
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE birthday_promo ENABLE ROW LEVEL SECURITY;
ALTER TABLE birthday_promo FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON birthday_promo
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON bookings
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE cash_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON cash_log
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE client_chat_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_chat_state FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON client_chat_state
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE client_history_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_history_cache FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON client_history_cache
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE client_marketing_last ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_marketing_last FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON client_marketing_last
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE client_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_preferences FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON client_preferences
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON clients
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE consents FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON consents
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE cutmatch_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE cutmatch_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON cutmatch_usage
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE cycle_reminder_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE cycle_reminder_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON cycle_reminder_log
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE freed_slot_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE freed_slot_offers FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON freed_slot_offers
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE gift_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE gift_certificates FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON gift_certificates
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE loyalty_redeem_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_redeem_codes FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON loyalty_redeem_codes
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE loyalty_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_transactions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON loyalty_transactions
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE master_push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE master_push_subscriptions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON master_push_subscriptions
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE masters_telegram ENABLE ROW LEVEL SECURITY;
ALTER TABLE masters_telegram FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON masters_telegram
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE maya_tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE maya_tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON maya_tenants
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE notify_prefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notify_prefs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON notify_prefs
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE payment_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_idempotency FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON payment_idempotency
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE processed_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE processed_records FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON processed_records
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE reactivation_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE reactivation_log FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON reactivation_log
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE record_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE record_state FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON record_state
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_codes FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON referral_codes
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE referral_promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_promos FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON referral_promos
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON referrals
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE review_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON review_requests
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE salon_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE salon_expenses FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON salon_expenses
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE salon_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE salon_rules FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON salon_rules
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON settings
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE slot_waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE slot_waitlist FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON slot_waitlist
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE staff_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON staff_messages
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE stylist_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE stylist_consents FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON stylist_consents
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON subscriptions
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tips
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE tool_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_audit FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON tool_audit
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE visit_mood ENABLE ROW LEVEL SECURITY;
ALTER TABLE visit_mood FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON visit_mood
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE web_login_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE web_login_codes FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON web_login_codes
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
ALTER TABLE web_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE web_sessions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON web_sessions
  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);
