#!/usr/bin/env python3
"""
SaaS Этап 0 — генератор Postgres-схемы из РЕАЛЬНОЙ боевой SQLite-схемы.

Вход:  /tmp/prod_schema.sql  (дамп sqlite_master с сервера, только структура)
Выход: 01_schema_postgres.sql (рядом)

Что делает:
  * транспилирует типы SQLite→Postgres через sqlglot;
  * INTEGER → BIGINT (telegram/record id > 2.1 млрд не влезают в INT);
  * AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
    (BY DEFAULT — чтобы при миграции можно было вставлять СВОИ id и сохранить FK);
  * добавляет tenant_id во все таблицы (+ FK на tenants);
  * 🔴 делает уникальности ПЕР-ТЕНАНТНЫМИ (один человек = клиент нескольких салонов);
  * PK доменных таблиц (client_id/record_id/key/...) → составной с tenant_id;
  * индексы — с tenant_id впереди (запросы всегда фильтруют по тенанту);
  * включает Row-Level Security на каждую таблицу.
Каждый итоговый стейтмент проверяется парсером sqlglot (диалект postgres).
"""
import re, sys, sqlglot
from sqlglot import exp

SRC = "/tmp/prod_schema.sql"
OUT = __file__.rsplit("/", 1)[0] + "/01_schema_postgres.sql"

# ── Решения мультитенантности (ручные, по смыслу данных) ──────────────────
# Инлайновые UNIQUE-колонки, которые становятся UNIQUE(tenant_id, col):
UNIQUE_SCOPE = {
    "admins": ["telegram_user_id"],
    "clients": ["telegram_chat_id"],          # 🔴 один человек — клиент многих салонов
    "birthday_promo": ["code"],
    "gift_certificates": ["code"],
    "masters_telegram": ["yclients_staff_id", "telegram_chat_id", "bind_code"],
    "referral_codes": ["code"],
    "referral_promos": ["code"],
}
# Доменный PK (НЕ суррогатный id) → составной (tenant_id, ...):
PK_COMPOSITE = {
    "client_chat_state": ["client_id"],
    "client_history_cache": ["client_id"],
    "cutmatch_usage": ["user_id", "day"],
    "loyalty_redeem_codes": ["code"],
    "processed_records": ["record_id"],
    "record_state": ["record_id"],
    "referral_codes": ["client_id"],
    "settings": ["key"],
}
# Таблично-уровневые UNIQUE(...) → с tenant_id впереди:
TABLE_UNIQUE_SCOPE = {
    "review_requests": ("client_id", "record_id"),
}
# web_sessions.token / web_login_codes.id — оставляем глобальными PK (рандомные),
# tenant_id добавляем просто колонкой для фильтрации.


def parse_dump(text):
    """[(kind, name, sql), ...] из дампа с маркерами '-- [table] name'."""
    out = []
    for m in re.finditer(r"-- \[(table|index)\] (\S+)\n(.*?;)\n", text, re.DOTALL):
        out.append((m.group(1), m.group(2), m.group(3).rstrip(";").strip()))
    return out


# ── Хелперы AST: «выдернуть» готовый узел из вспомогательного CREATE TABLE ──
def _pluck(ddl_pg, idx):
    return sqlglot.parse_one(ddl_pg, read="postgres").this.expressions[idx]

def _tenant_col():
    # DEFAULT из сессии: старый код, вставляющий БЕЗ tenant_id, сам подставит
    # текущий салон (SET app.tenant_id). Если салон не задан — INSERT упадёт
    # (NOT NULL ловит NULL) — это «отказ громко», а не тихая утечка.
    return _pluck(
        "CREATE TABLE _(tenant_id BIGINT NOT NULL "
        "DEFAULT current_setting('app.tenant_id')::bigint REFERENCES tenants(id))", 0)

def _uniq(cols):
    return _pluck(f"CREATE TABLE _(x BIGINT, UNIQUE ({', '.join(cols)}))", 1)

def _pk(cols):
    return _pluck(f"CREATE TABLE _(x BIGINT, PRIMARY KEY ({', '.join(cols)}))", 1)

def _coldef(schema, colname):
    for e in schema.expressions:
        if isinstance(e, exp.ColumnDef) and e.name == colname:
            return e
    return None

def _strip_kind(coldef, kind_cls):
    cons = coldef.args.get("constraints") or []
    coldef.set("constraints", [c for c in cons if not isinstance(c.args.get("kind"), kind_cls)])


# Родительские таблицы FK (clients/referrals) — им нужен UNIQUE(tenant_id, id),
# чтобы на них можно было сослаться композитным FK.
FK_TARGETS = set()


def _composite_fk(fk_sql):
    """'FOREIGN KEY (client_id) REFERENCES clients (id)' →
       'FOREIGN KEY (tenant_id, client_id) REFERENCES clients (tenant_id, id)'."""
    m = re.match(r"FOREIGN KEY \(([^)]+)\) REFERENCES (\w+) \(([^)]+)\)", fk_sql)
    if not m:
        return fk_sql, None
    cols, target, refcols = m.group(1), m.group(2), m.group(3)
    return (f"FOREIGN KEY (tenant_id, {cols}) REFERENCES {target} (tenant_id, {refcols})",
            target)


def transform_table(name, ddl_sqlite):
    """SQLite CREATE TABLE → Postgres, через манипуляцию AST (надёжно)."""
    node = sqlglot.parse_one(ddl_sqlite, read="sqlite")
    # INTEGER → BIGINT (telegram/record id > 2.1 млрд)
    for dt in node.find_all(exp.DataType):
        if dt.this == exp.DataType.Type.INT:
            dt.set("this", exp.DataType.Type.BIGINT)

    schema = node.this
    items = list(schema.expressions)
    added = []   # новые табличные ограничения

    # 1) инлайновый UNIQUE → пер-тенантный табличный UNIQUE(tenant_id, col)
    for col in UNIQUE_SCOPE.get(name, []):
        cd = _coldef(schema, col)
        if cd:
            _strip_kind(cd, exp.UniqueColumnConstraint)
        added.append(_uniq(["tenant_id", col]))

    # 2) табличный UNIQUE(...) → с tenant_id впереди
    if name in TABLE_UNIQUE_SCOPE:
        cols = list(TABLE_UNIQUE_SCOPE[name])
        items = [e for e in items if not isinstance(e, exp.UniqueColumnConstraint)]
        added.append(_uniq(["tenant_id", *cols]))

    # 3) доменный PK → составной (tenant_id, ...)
    if name in PK_COMPOSITE:
        cols = list(PK_COMPOSITE[name])
        for col in cols:
            cd = _coldef(schema, col)
            if cd:
                _strip_kind(cd, exp.PrimaryKeyColumnConstraint)
        items = [e for e in items if not isinstance(e, exp.PrimaryKey)]
        added.append(_pk(["tenant_id", *cols]))

    # 4) вынести доменные FK (client_id→clients и т.п.) в отдельные ALTER —
    #    иначе порядок создания таблиц ломает ссылки. tenant_id-FK остаётся
    #    инлайном (tenants создаётся первой, в HEADER).
    #    🔴 АУДИТ-ФИКС: FK делаем КОМПОЗИТНЫМИ (tenant_id, col) → parent(tenant_id, id),
    #    иначе салон A мог сослаться на клиента салона B (FK-проверка обходит RLS).
    fks = [e for e in items if isinstance(e, exp.ForeignKey)]
    items = [e for e in items if not isinstance(e, exp.ForeignKey)]

    # 5) колонка tenant_id впереди + собрать дерево заново
    schema.set("expressions", [_tenant_col()] + items + added)
    create_sql = node.sql(dialect="postgres", pretty=True) + ";"
    alters = []
    for fk in fks:
        comp, target = _composite_fk(fk.sql(dialect="postgres"))
        if target:
            FK_TARGETS.add(target)
        alters.append(f"ALTER TABLE {name} ADD {comp};")
    return create_sql, alters


def transform_index(name, ddl_sqlite):
    """SQLite индекс → Postgres, tenant_id впереди списка колонок."""
    pg = sqlglot.transpile(ddl_sqlite, read="sqlite", write="postgres")[0]
    pg = re.sub(r"\bINT\b", "BIGINT", pg)
    pg = re.sub(r"(ON\s+\w+\s*\()", r"\1tenant_id, ", pg, count=1)
    return pg.rstrip(";") + ";"


HEADER = """-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  SaaS Этап 0 — Postgres-схема (СГЕНЕРИРОВАНО из боевой SQLite).     ║
-- ║  Текущий салон при миграции = tenant_id 1.                         ║
-- ║  НЕ редактировать руками — править generate.py и пересобирать.      ║
-- ╚══════════════════════════════════════════════════════════════════╝

-- ── 0. Реестр тенантов и биллинг платформы (новое) ───────────────────────
CREATE TABLE tenants (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug               TEXT UNIQUE NOT NULL,
  display_name       TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'trial',
  plan               TEXT NOT NULL DEFAULT 'start',
  brand              JSONB NOT NULL DEFAULT '{}',
  provider           TEXT NOT NULL DEFAULT 'yclients',
  provider_config    BYTEA,
  active_master_ids  JSONB NOT NULL DEFAULT '[]',
  bot_mode           TEXT NOT NULL DEFAULT 'shared',
  bot_config         BYTEA,
  admin_tg_ids       JSONB NOT NULL DEFAULT '[]',
  payments_config    BYTEA,
  settings           JSONB NOT NULL DEFAULT '{}',
  locale             TEXT NOT NULL DEFAULT 'ru',
  timezone           TEXT NOT NULL DEFAULT 'Europe/Moscow',
  trial_ends_at      TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  billing_method_id  TEXT,
  owner_email        TEXT,
  owner_phone        TEXT,
  owner_tg_id        BIGINT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tenant_invoices (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id          BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  period_start       DATE NOT NULL,
  period_end         DATE NOT NULL,
  plan               TEXT NOT NULL,
  amount_rub         BIGINT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'pending',
  yukassa_payment_id TEXT,
  paid_at            TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_tenant_invoices_tenant ON tenant_invoices (tenant_id, period_start);

-- Подключённые допы-модули салона (конструктор тарифов). Ключи — plan_catalog.ADDONS.
CREATE TABLE tenant_addons (
  tenant_id  BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  addon_key  TEXT NOT NULL,
  active     BOOLEAN NOT NULL DEFAULT true,
  enabled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, addon_key)
);

-- Помесячный счётчик использования метрик-фич (CutMatch и др.) для квот и сверх-оплаты.
CREATE TABLE tenant_usage (
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  feature   TEXT NOT NULL,
  ym        TEXT NOT NULL,              -- '2026-06'
  count     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, feature, ym)
);

-- Текущий салон → tenant 1 (бренд/секреты заполнить отдельно скриптом миграции)
INSERT INTO tenants (id, slug, display_name)
  OVERRIDING SYSTEM VALUE VALUES (1, 'malesthetic', 'Мужская Эстетика');
"""


def main():
    text = open(SRC, encoding="utf-8").read()
    items = parse_dump(text)
    tables = [(n, s) for k, n, s in items if k == "table"]
    indexes = [(n, s) for k, n, s in items if k == "index"]

    out = [HEADER, "\n-- ── 1. Доменные таблицы (+ tenant_id, per-tenant uniq) ──────────────────"]
    table_names = []
    table_ddls = {}
    fk_alters = []
    for name, ddl in tables:
        table_names.append(name)
        pg, alters = transform_table(name, ddl)
        table_ddls[name] = pg
        fk_alters += alters
        out.append("\n" + pg)

    out.append("\n-- ── 1a. UNIQUE(tenant_id, id) на родителях FK — для композитных FK ──")
    for t in sorted(FK_TARGETS):
        out.append(f"ALTER TABLE {t} ADD CONSTRAINT uq_{t}_tenant_id UNIQUE (tenant_id, id);")

    out.append("\n-- ── 1b. Внешние ключи КОМПОЗИТНЫЕ (tenant_id + col) → parent(tenant_id, id) ──")
    out.append("-- 🔴 АУДИТ-ФИКС: запрещает ссылку на клиента ЧУЖОГО салона (FK обходил RLS).")
    out += fk_alters

    out.append("\n-- ── 2. Индексы (tenant_id впереди) ─────────────────────────────────────")
    index_ddls = []
    for name, ddl in indexes:
        pg = transform_index(name, ddl)
        index_ddls.append(pg)
        out.append(pg)
    # + индекс по tenant_id на каждую таблицу
    for t in table_names:
        out.append(f"CREATE INDEX idx_{t}_tenant ON {t} (tenant_id);")

    out.append("\n-- ── 3. Row-Level Security — изоляция тенантов на уровне БД ─────────────")
    out.append("-- Приложение в начале запроса делает: SET app.tenant_id = '<id>';")
    for t in table_names:
        out.append(
            f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;\n"
            f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY;\n"
            f"CREATE POLICY tenant_isolation ON {t}\n"
            f"  USING (tenant_id = current_setting('app.tenant_id', true)::bigint)\n"
            f"  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::bigint);"
        )

    sql = "\n".join(out) + "\n"
    open(OUT, "w", encoding="utf-8").write(sql)

    # ── СТРОГАЯ валидация: каждый CREATE TABLE/INDEX парсится Postgres-диалектом
    #    ИМЕННО как Create-узел (а не fallback в generic Command). ──
    errors = 0
    import warnings
    for name, ddl in {**table_ddls}.items():
        try:
            with warnings.catch_warnings():
                node = sqlglot.parse_one(ddl, read="postgres", error_level="raise")
            if not isinstance(node, exp.Create):
                errors += 1; print(f"❌ TABLE {name}: распарсилось как {type(node).__name__}, не Create")
        except Exception as e:
            errors += 1; print(f"❌ TABLE {name}: {e}")
    for ddl in index_ddls:
        try:
            node = sqlglot.parse_one(ddl, read="postgres", error_level="raise")
            if not isinstance(node, exp.Create):
                errors += 1; print(f"❌ INDEX распарсился как {type(node).__name__}: {ddl[:80]}")
        except Exception as e:
            errors += 1; print(f"❌ INDEX: {e} :: {ddl[:80]}")
    # RLS/POLICY sqlglot не моделирует (это нормально) — их Postgres примет.
    print(f"Таблиц: {len(tables)} | индексов(исх): {len(indexes)} | строк SQL: {sql.count(chr(10))}")
    print(f"СТРОГАЯ валидация CREATE TABLE/INDEX: {'OK, все Create' if errors==0 else str(errors)+' ошибок'}")
    print(f"Записано: {OUT}")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
